name: V2ex

on:
  schedule:
    - cron: '0/10 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: yanglbme/v2ex-action@master
        with:
          webhook: ${{secrets.WEBHOOK}}
          count: 10
